In [ ]:
import pandas as pd
import json

In [ ]:
with open("/content/desert_lion_camera_traps.json") as file:
  data = json.load(file)

data

{'info': {'version': '2024.07.15_00',
  'description': 'Desert Lion Camera Traps'},
 'images': [{'id': 'acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1d607a6c-153c-4b05-a125-0cd90228bb0d/20150830-PICT0034.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1d607a6c-153c-4b05-a125-0cd90228bb0d/20150830-PICT0034.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0052.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0052.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0053.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0053.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0055.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0055.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0056.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0056.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0041.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0041.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0042.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0042.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0043.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0043.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0044.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0044.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0045.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3dbc2adb-2560-49c9-854a-05612272a3c6/20170218-PICT0045.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0046.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0046.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0047.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0047.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0048.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0048.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0049.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0049.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0050.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0050.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0058.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0058.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0059.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0059.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0060.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0060.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0061.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0061.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ae7b1243-f844-4593-9372-8eb18658f182/20170218-PICT0062.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ae7b1243-f844-4593-9372-8eb18658f182/20170218-PICT0062.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ae7b1243-f844-4593-9372-8eb18658f182/20170218-PICT0063.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ae7b1243-f844-4593-9372-8eb18658f182/20170218-PICT0063.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ae7b1243-f844-4593-9372-8eb18658f182/20170218-PICT0064.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ae7b1243-f844-4593-9372-8eb18658f182/20170218-PICT0064.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0007.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0007.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0009.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0009.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0011.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0011.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0020.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0020.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0023.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0023.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0024.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0024.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0025.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0025.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0026.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0026.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0027.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0027.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0031.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0031.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0033.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0033.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0034.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0034.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0035.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0035.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0037.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0037.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0040.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/2017/02/PvL_seq_ce06c81a-9511-410f-a341-5ae8b42891d6/20170218-PICT0040.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_060de991-6775-4ac6-b854-e4b91def17e4/20150622-PICT0013.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_060de991-6775-4ac6-b854-e4b91def17e4/20150622-PICT0013.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_060de991-6775-4ac6-b854-e4b91def17e4/20150622-PICT0014.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_060de991-6775-4ac6-b854-e4b91def17e4/20150622-PICT0014.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_060de991-6775-4ac6-b854-e4b91def17e4/20150622-PICT0015.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_060de991-6775-4ac6-b854-e4b91def17e4/20150622-PICT0015.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_0f942e5d-01dc-451e-b380-9851ec746c48/20150622-PICT0034.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_0f942e5d-01dc-451e-b380-9851ec746c48/20150622-PICT0034.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_0f942e5d-01dc-451e-b380-9851ec746c48/20150622-PICT0035.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_0f942e5d-01dc-451e-b380-9851ec746c48/20150622-PICT0035.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_0f942e5d-01dc-451e-b380-9851ec746c48/20150622-PICT0036.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_0f942e5d-01dc-451e-b380-9851ec746c48/20150622-PICT0036.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_1059b853-22e5-49e8-b55c-5c3bd2c0dabc/20150622-PICT0092.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_1059b853-22e5-49e8-b55c-5c3bd2c0dabc/20150622-PICT0092.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_140ea8b5-2b27-4483-82dd-144f8cdee2e1/20150622-PICT0058.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_140ea8b5-2b27-4483-82dd-144f8cdee2e1/20150622-PICT0058.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_140ea8b5-2b27-4483-82dd-144f8cdee2e1/20150622-PICT0059.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_140ea8b5-2b27-4483-82dd-144f8cdee2e1/20150622-PICT0059.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_269f0117-a512-4ac7-b9b3-a7f6880d4a0e/20150622-PICT0088.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_269f0117-a512-4ac7-b9b3-a7f6880d4a0e/20150622-PICT0088.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_2bfd5573-dd09-4aea-b4cd-432c181eaf55/20150622-PICT0028.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_2bfd5573-dd09-4aea-b4cd-432c181eaf55/20150622-PICT0028.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_2bfd5573-dd09-4aea-b4cd-432c181eaf55/20150622-PICT0029.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_2bfd5573-dd09-4aea-b4cd-432c181eaf55/20150622-PICT0029.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_2bfd5573-dd09-4aea-b4cd-432c181eaf55/20150622-PICT0030.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_2bfd5573-dd09-4aea-b4cd-432c181eaf55/20150622-PICT0030.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_3dec4ea2-e929-48e6-b97b-9b0cb2b9588b/20150622-PICT0019.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_3dec4ea2-e929-48e6-b97b-9b0cb2b9588b/20150622-PICT0019.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_3dec4ea2-e929-48e6-b97b-9b0cb2b9588b/20150622-PICT0020.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_3dec4ea2-e929-48e6-b97b-9b0cb2b9588b/20150622-PICT0020.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_3dec4ea2-e929-48e6-b97b-9b0cb2b9588b/20150622-PICT0021.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_3dec4ea2-e929-48e6-b97b-9b0cb2b9588b/20150622-PICT0021.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4090ce8e-3f35-4e9d-bc2c-ee3d1d6348d5/20150622-PICT0049.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4090ce8e-3f35-4e9d-bc2c-ee3d1d6348d5/20150622-PICT0049.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4090ce8e-3f35-4e9d-bc2c-ee3d1d6348d5/20150622-PICT0050.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4090ce8e-3f35-4e9d-bc2c-ee3d1d6348d5/20150622-PICT0050.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4090ce8e-3f35-4e9d-bc2c-ee3d1d6348d5/20150622-PICT0051.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4090ce8e-3f35-4e9d-bc2c-ee3d1d6348d5/20150622-PICT0051.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_43292810-4d1b-4758-bc38-24ff912ce863/20150622-PICT0043.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_43292810-4d1b-4758-bc38-24ff912ce863/20150622-PICT0043.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_43292810-4d1b-4758-bc38-24ff912ce863/20150622-PICT0044.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_43292810-4d1b-4758-bc38-24ff912ce863/20150622-PICT0044.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_43292810-4d1b-4758-bc38-24ff912ce863/20150622-PICT0045.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_43292810-4d1b-4758-bc38-24ff912ce863/20150622-PICT0045.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4591137b-6455-46f8-8c03-8a4f4e749ec6/20150622-PICT0064.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4591137b-6455-46f8-8c03-8a4f4e749ec6/20150622-PICT0064.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4591137b-6455-46f8-8c03-8a4f4e749ec6/20150622-PICT0065.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4591137b-6455-46f8-8c03-8a4f4e749ec6/20150622-PICT0065.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4591137b-6455-46f8-8c03-8a4f4e749ec6/20150622-PICT0066.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_4591137b-6455-46f8-8c03-8a4f4e749ec6/20150622-PICT0066.JPG',
   'location': 'unknown',
   'datetime': '2012:01:01 01:01:01'},
  {'id': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_465c7540-0257-4681-8c17-94a167c3bad1/20150622-PICT0025.JPG',
   'file_name': 'acinonyx jubatus/Camera Trap/Events/Aj_Huab/2015/06/PvL_seq_465c7540-0257-4681-8c17-94a167c3bad1/20150622-PICT0025.JPG',
   'location': 'unknown',

In [ ]:
print(data.keys())

dict_keys(['info', 'images', 'annotations', 'categories'])

In [ ]:
image_df = pd.DataFrame(data['images'])
annotation_df = pd.DataFrame(data['annotations'])
category_df = pd.DataFrame(data['categories'])

In [ ]:
image_df.head()

,id,file_name,location,datetime
0,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,unknown,2012:01:01 01:01:01
1,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
2,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
3,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
4,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01

In [ ]:
annotation_df.head()

,image_id,id,sequence_level_annotation,category_id
0,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,False,0
1,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0
2,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0
3,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0
4,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0

In [ ]:
category_df

                        name  id
0           acinonyx jubatus   0
1      alopochen aegyptiacus   1
2     antidorcas marsupialis   2
3                       aves   3
4                 bos taurus   4
5            canis mesomelas   5
6              cn-francolins   6
7        cn-other carnivores   7
8                    cn-owls   8
9                 cn-raptors   9
10                columbidae  10
11              corvus albus  11
12           corvus capensis  12
13           crocuta crocuta  13
14          diceros bicornis  14
15              equus asinus  15
16    equus zebra hartmannae  16
17      eupodotis rueppellii  17
18               felis catus  18
19              felis lybica  19
20       galerella sanguinea  20
21           genetta genetta  21
22    giraffa camelopardalis  22
23            gyps africanus  23
24            hyaena brunnea  24
25  hystrix africaeaustralis  25
26            lepus capensis  26
27        loxodanta africana  27
28        mellivora capensis  28
29           neotis ludwigii  29
30                 numididae  30
31     oreotragus oreotragus  31
32              oryx gazella  32
33         otocyon megalotis  33
34              panthera leo  34
35           panthera pardus  35
36              papio anubis  36
37         procavia capensis  37
38      pronolagus randensis  38
39        proteles cristatus  39
40               pteroclidae  40
41     raphiceros campestris  41
42          struthio camelus  42
43       torgos tracheliotos  43
44  tragelaphus strepsiceros  44
45              vulpes chama  45

In [ ]:
image_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63468 entries, 0 to 63467
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         63468 non-null  object
 1   file_name  63468 non-null  object
 2   location   63468 non-null  object
 3   datetime   63259 non-null  object
dtypes: object(4)
memory usage: 1.9+ MB

In [ ]:
annotation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63468 entries, 0 to 63467
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   image_id                   63468 non-null  object
 1   id                         63468 non-null  object
 2   sequence_level_annotation  63468 non-null  bool
 3   category_id                63468 non-null  int64
dtypes: bool(1), int64(1), object(2)
memory usage: 1.5+ MB

In [ ]:
category_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    46 non-null     object
 1   id      46 non-null     int64
dtypes: int64(1), object(1)
memory usage: 868.0+ bytes

In [ ]:
annotation_df['image_id'].value_counts()

image_id
vulpes chama/Camera Trap2/PvL_seq_f8170ba2-e56d-4040-945b-73daf10e3ee0/CDY_0009.JPG                        1
acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1d607a6c-153c-4b05-a125-0cd90228bb0d/20150830-PICT0034.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0052.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0053.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_362e9fdb-9291-4647-894b-fe0bc7245b2b/20170218-PICT0055.JPG    1
                                                                                                          ..
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0059.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_837b1a6e-1413-4303-b34c-5f45d6f6ee18/20170218-PICT0058.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0050.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0049.JPG    1
acinonyx jubatus/Camera Trap/2017/02/PvL_seq_5d46c4d1-d79f-4530-85e4-f38c11f8779d/20170218-PICT0048.JPG    1
Name: count, Length: 63468, dtype: int64

In [ ]:
annotation_df['category_id'].value_counts()

category_id
32    16499
16    11687
24     7814
42     6076
2      3457
22     2935
14     2736
40     1783
34     1730
5      1462
27     1434
13     1121
43      709
25      544
11      511
0       450
35      410
29      308
9       281
41      264
36      256
38      117
3       104
28       97
6        77
37       76
10       71
30       66
26       55
44       54
45       38
17       35
15       34
8        33
12       26
31       25
33       22
7        13
39       12
4        11
20       10
1         7
18        7
19        5
23        3
21        3
Name: count, dtype: int64

In [ ]:
category_df

                        name  id
0           acinonyx jubatus   0
1      alopochen aegyptiacus   1
2     antidorcas marsupialis   2
3                       aves   3
4                 bos taurus   4
5            canis mesomelas   5
6              cn-francolins   6
7        cn-other carnivores   7
8                    cn-owls   8
9                 cn-raptors   9
10                columbidae  10
11              corvus albus  11
12           corvus capensis  12
13           crocuta crocuta  13
14          diceros bicornis  14
15              equus asinus  15
16    equus zebra hartmannae  16
17      eupodotis rueppellii  17
18               felis catus  18
19              felis lybica  19
20       galerella sanguinea  20
21           genetta genetta  21
22    giraffa camelopardalis  22
23            gyps africanus  23
24            hyaena brunnea  24
25  hystrix africaeaustralis  25
26            lepus capensis  26
27        loxodanta africana  27
28        mellivora capensis  28
29           neotis ludwigii  29
30                 numididae  30
31     oreotragus oreotragus  31
32              oryx gazella  32
33         otocyon megalotis  33
34              panthera leo  34
35           panthera pardus  35
36              papio anubis  36
37         procavia capensis  37
38      pronolagus randensis  38
39        proteles cristatus  39
40               pteroclidae  40
41     raphiceros campestris  41
42          struthio camelus  42
43       torgos tracheliotos  43
44  tragelaphus strepsiceros  44
45              vulpes chama  45

In [ ]:
merged_df = annotation_df.merge(
    category_df,
    left_on='category_id',
    right_on='id',
    how='left'
)

In [ ]:
merged_df.head()

,image_id,id_x,sequence_level_annotation,category_id,name,id_y
0,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,False,0,acinonyx jubatus,0
1,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,0
2,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,0
3,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,0
4,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,0

In [ ]:
merged_df = merged_df.drop(columns=['id_x', 'id_y'], axis=1)

In [ ]:
merged_df = merged_df.rename(columns={'name': 'species'})

In [ ]:
merged_df.head()

,image_id,sequence_level_annotation,category_id,species
0,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,False,0,acinonyx jubatus
1,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus
2,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus
3,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus
4,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus

In [ ]:
df = merged_df.merge(
    image_df,
    left_on='image_id',
    right_on='id',
    how='left'
)

In [ ]:
df

,image_id,sequence_level_annotation,category_id,species,id,file_name,location,datetime
0,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,False,0,acinonyx jubatus,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,unknown,2012:01:01 01:01:01
1,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
2,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
3,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
4,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,unknown,2012:01:01 01:01:01
...,...,...,...,...,...,...,...,...
63463,vulpes chama/Camera Trap2/PvL_seq_a06bbb02-b82...,False,45,vulpes chama,vulpes chama/Camera Trap2/PvL_seq_a06bbb02-b82...,vulpes chama/Camera Trap2/PvL_seq_a06bbb02-b82...,unknown,2007:08:04 19:22:00
63464,vulpes chama/Camera Trap2/PvL_seq_a6d79586-4cb...,False,45,vulpes chama,vulpes chama/Camera Trap2/PvL_seq_a6d79586-4cb...,vulpes chama/Camera Trap2/PvL_seq_a6d79586-4cb...,unknown,2007:08:03 20:14:00
63465,vulpes chama/Camera Trap2/PvL_seq_b1311612-96b...,False,45,vulpes chama,vulpes chama/Camera Trap2/PvL_seq_b1311612-96b...,vulpes chama/Camera Trap2/PvL_seq_b1311612-96b...,unknown,2007:08:03 19:58:00
63466,vulpes chama/Camera Trap2/PvL_seq_c8032da6-815...,False,45,vulpes chama,vulpes chama/Camera Trap2/PvL_seq_c8032da6-815...,vulpes chama/Camera Trap2/PvL_seq_c8032da6-815...,unknown,2007:08:03 22:53:00
63467,vulpes chama/Camera Trap2/PvL_seq_f8170ba2-e56...,False,45,vulpes chama,vulpes chama/Camera Trap2/PvL_seq_f8170ba2-e56...,vulpes chama/Camera Trap2/PvL_seq_f8170ba2-e56...,unknown,2007:08:03 23:06:00

In [ ]:
df = df.drop(columns=['id', 'file_name'], axis=1)

In [ ]:
df

,image_id,sequence_level_annotation,category_id,species,location,datetime
0,acinonyx jubatus/Camera Trap/2015/08/PvL_seq_1...,False,0,acinonyx jubatus,unknown,2012:01:01 01:01:01
1,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,unknown,2012:01:01 01:01:01
2,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,unknown,2012:01:01 01:01:01
3,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,unknown,2012:01:01 01:01:01
4,acinonyx jubatus/Camera Trap/2017/02/PvL_seq_3...,False,0,acinonyx jubatus,unknown,2012:01:01 01:01:01
...,...,...,...,...,...,...
63463,vulpes chama/Camera Trap2/PvL_seq_a06bbb02-b82...,False,45,vulpes chama,unknown,2007:08:04 19:22:00
63464,vulpes chama/Camera Trap2/PvL_seq_a6d79586-4cb...,False,45,vulpes chama,unknown,2007:08:03 20:14:00
63465,vulpes chama/Camera Trap2/PvL_seq_b1311612-96b...,False,45,vulpes chama,unknown,2007:08:03 19:58:00
63466,vulpes chama/Camera Trap2/PvL_seq_c8032da6-815...,False,45,vulpes chama,unknown,2007:08:03 22:53:00
63467,vulpes chama/Camera Trap2/PvL_seq_f8170ba2-e56...,False,45,vulpes chama,unknown,2007:08:03 23:06:00

In [ ]:
df['datetime'].value_counts().head()

datetime
2012:01:01 01:01:01    16387
2013:02:10 04:27:30        6
2013:02:15 20:51:57        4
2013:02:17 09:49:38        4
2013:02:14 12:07:06        4
Name: count, dtype: int64

In [ ]:
common_names = {
    "oryx gazella": "Oryx/Gemsbok",
    "equus zebra hartmannae": "Hartmann's mountain zebra",
    "hyaena brunnea": "Brown hyena",
    "struthio camelus": "Ostrich",
    "antidorcas marsupialis": "Springbok",
    "giraffa camelopardalis": "Giraffe",
    "diceros bicornis": "Black rhino",
    "panthera leo": "Lion",
    "canis mesomelas": "Black-backed jackal",
    "loxodanta africana": "Elephant",
}

In [ ]:
subset_df = df[df['species'].isin(common_names.keys())].copy()
subset_df['common_name'] = subset_df['species'].map(common_names)

In [ ]:
SOFT_CAP = 2000  # bounds training time, but doesn't force equal counts

capped_df = (
    subset_df.groupby("species", group_keys=False)
    .apply(lambda x: x.sample(n=min(len(x), SOFT_CAP), random_state=42))
)

/tmp/ipykernel_2024/2027388500.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=min(len(x), SOFT_CAP), random_state=42))

In [ ]:
capped_df

,image_id,sequence_level_annotation,category_id,species,location,datetime,common_name
2232,antidorcas marsupialis/Camera Trap/North/Gania...,False,2,antidorcas marsupialis,unknown,2013:08:03 12:28:55,Springbok
508,antidorcas marsupialis/Camera Trap/2014/09/PvL...,False,2,antidorcas marsupialis,unknown,2012:01:01 01:01:01,Springbok
651,antidorcas marsupialis/Camera Trap/2017/01/PvL...,False,2,antidorcas marsupialis,unknown,2012:01:01 01:01:01,Springbok
3213,antidorcas marsupialis/Camera Trap/North/Okong...,False,2,antidorcas marsupialis,unknown,2012:01:01 01:01:01,Springbok
2476,antidorcas marsupialis/Camera Trap/North/Okong...,False,2,antidorcas marsupialis,unknown,2012:02:21 08:23:24,Springbok
...,...,...,...,...,...,...,...
60745,struthio camelus/Camera Trap/North/Ganias/2013...,False,42,struthio camelus,unknown,2013:08:03 13:59:09,Ostrich
61959,struthio camelus/Camera Trap/North/Okongwe/29N...,False,42,struthio camelus,unknown,2011:11:08 11:59:29,Ostrich
56808,struthio camelus/Camera Trap/2017/04/PvL_seq_8...,False,42,struthio camelus,unknown,2012:01:01 01:01:01,Ostrich
61929,struthio camelus/Camera Trap/North/Okongwe/201...,False,42,struthio camelus,unknown,2012:01:01 01:01:01,Ostrich
59332,struthio camelus/Camera Trap/North/Ganias/2013...,False,42,struthio camelus,unknown,2013:07:22 13:51:43,Ostrich

In [ ]:
capped_df.to_csv('manifest_metadata.csv', index=False)